#!/usr/bin/env bash
# Brings the whole NEXUS system up: gateway -> databases -> services -> seed -> frontend.
# Waits on health checks, never on sleep.
#   scripts/start-all.sh              start (build images only if missing)
#   scripts/start-all.sh --build      rebuild every service image
#   scripts/start-all.sh --clean      wipe containers and volumes first (fresh databases)
#   scripts/start-all.sh --no-frontend  backend only
set -euo pipefail
. "$(cd "$(dirname "$0")" && pwd)/lib.sh"

BUILD=0; CLEAN=0; FRONTEND=1
for a in "$@"; do
  case "$a" in
    --build) BUILD=1 ;; --clean) CLEAN=1 ;; --no-frontend) FRONTEND=0 ;;
    -h|--help) sed -n '2,9p' "$0"; exit 0 ;;
    *) c_fail "unknown flag $a"; exit 2 ;;
  esac
done
cd "$ROOT"; mkdir -p "$RUN_DIR"

command -v docker >/dev/null || { c_fail "docker is required"; exit 1; }
docker info >/dev/null 2>&1 || { c_fail "the Docker daemon is not running. Start Docker Desktop and retry."; exit 1; }
command -v node >/dev/null || { c_fail "node 18+ is required"; exit 1; }
command -v curl >/dev/null || { c_fail "curl is required"; exit 1; }

[ "$CLEAN" = 1 ] && "$ROOT/scripts/stop-all.sh" --clean

# ---- secrets: generated once, never committed ----
if [ ! -f "$ROOT/.env" ]; then
  rnd() { LC_ALL=C tr -dc 'a-z0-9' </dev/urandom | head -c 24; }
  cat >"$ROOT/.env" <<ENV
# Generated by scripts/start-all.sh. Gitignored. Delete to regenerate.
JWT_SECRET=$(rnd)
SERVICE_KEY=$(rnd)
POSTGRES_PASSWORD=$(rnd)
NEO4J_PASSWORD=$(rnd)
RABBITMQ_USER=nexus
RABBITMQ_PASS=$(rnd)
MINIO_ROOT_USER=nexus
MINIO_ROOT_PASSWORD=$(rnd)
DEMO_MODE=true
DEMO_CONTROLLER_PASSWORD=$(rnd)
DEMO_RESPONDER_PASSWORD=$(rnd)
DEMO_CITIZEN_PASSWORD=$(rnd)
ENV
  c_info "wrote .env with fresh secrets"
fi
load_env

# ---- host ports: keep ours if already running, else pick a free one (8000 may belong to another project) ----
pick_or_keep() { # var, container, container-port, candidates...
  local var="$1" cont="$2" cport="$3"; shift 3
  local cur; cur="$(published_port "$cont" "$cport")"
  if [ -n "$cur" ]; then eval "$var=$cur"; return; fi
  local p; p="$(pick_port "$@")" || { c_fail "no free port for $var"; exit 1; }
  eval "$var=$p"
}
pick_or_keep GATEWAY_PORT nexus-traefik 80 "${GATEWAY_PORT:-8000}" 8010 8011 8012 8013
pick_or_keep TRAEFIK_DASHBOARD_PORT nexus-traefik 8080 8081 8082 8083
pick_or_keep RABBITMQ_PORT nexus-rabbitmq 5672 5672 5673 5674
pick_or_keep RABBITMQ_MGMT_PORT nexus-rabbitmq 15672 15672 15673 15674
pick_or_keep MINIO_PORT nexus-minio 9000 9000 9002 9003
pick_or_keep MINIO_CONSOLE_PORT nexus-minio 9001 9001 9004 9005
cat >"$RUN_DIR/ports.env" <<PORTS
GATEWAY_PORT=$GATEWAY_PORT
TRAEFIK_DASHBOARD_PORT=$TRAEFIK_DASHBOARD_PORT
RABBITMQ_PORT=$RABBITMQ_PORT
RABBITMQ_MGMT_PORT=$RABBITMQ_MGMT_PORT
MINIO_PORT=$MINIO_PORT
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT
PORTS
export GATEWAY_PORT TRAEFIK_DASHBOARD_PORT RABBITMQ_PORT RABBITMQ_MGMT_PORT MINIO_PORT MINIO_CONSOLE_PORT
[ "$GATEWAY_PORT" != 8000 ] && c_warn "port 8000 is taken by another program: the gateway uses $GATEWAY_PORT instead"

# ---- seed data from the frontend datasets ----
c_info "exporting seed data from frontend/src/data/index.js"
node "$ROOT/tools/seed/export-data.mjs" >/dev/null

# ---- 1. gateway: Traefik + RabbitMQ + MinIO + Redis ----
c_info "starting the gateway (Traefik, RabbitMQ, MinIO, Redis)"
docker compose -f "$GATEWAY_COMPOSE" up -d >"$RUN_DIR/gateway-up.log" 2>&1 || { c_fail "gateway failed to start, see .run/gateway-up.log"; exit 1; }
for c in nexus-traefik nexus-redis nexus-rabbitmq nexus-minio; do
  wait_healthy "$c" 150 || { c_fail "$c is not healthy (docker logs $c)"; exit 1; }
done
c_ok "gateway up on http://localhost:$GATEWAY_PORT"

# ---- 2. databases ----
c_info "starting databases"
pids=()
for s in "${SERVICES[@]}"; do
  d="$(db_of "$s")"; [ -z "$d" ] && continue
  cn="nexus-$s-db"; [ "$d" = neo4j ] && cn="nexus-$s-neo4j"
  ( docker compose -f "$(compose_of "$s")" up -d "$d" >"$RUN_DIR/db-$s.log" 2>&1 && { [ "$d" = neo4j ] || wait_healthy "$cn" 90; } || { c_fail "database for $s failed, see .run/db-$s.log"; exit 1; } ) &
  pids+=($!)
done
for p in "${pids[@]}"; do wait "$p"; done
c_ok "databases healthy"

# ---- 3. build images (4 at a time: kind to a laptop) ----
need_build=()
for s in "${SERVICES[@]}"; do
  if [ "$BUILD" = 1 ] || ! docker image inspect "nexus/$s:dev" >/dev/null 2>&1; then need_build+=("$s"); fi
done
if [ "${#need_build[@]}" -gt 0 ]; then
  c_info "building ${#need_build[@]} service image(s): ${need_build[*]}"
  build_one() { docker compose -f "$(compose_of "$1")" build "$1" >"$RUN_DIR/build-$1.log" 2>&1 || { c_fail "build failed: $1 (see .run/build-$1.log)"; return 1; }; }
  running=0; failed=0; bpids=()
  for s in "${need_build[@]}"; do
    build_one "$s" & bpids+=($!)
    running=$((running+1))
    if [ "$running" -ge 4 ]; then wait "${bpids[0]}" || failed=1; bpids=("${bpids[@]:1}"); running=$((running-1)); fi
  done
  for p in "${bpids[@]}"; do wait "$p" || failed=1; done
  [ "$failed" = 0 ] || exit 1
  c_ok "images built"
fi

# ---- 4. services ----
c_info "starting services"
pids=()
for s in "${SERVICES[@]}"; do
  ( docker compose -f "$(compose_of "$s")" up -d --no-build "$s" >"$RUN_DIR/up-$s.log" 2>&1 || { c_fail "$s failed to start, see .run/up-$s.log"; exit 1; } ) &
  pids+=($!)
done
for p in "${pids[@]}"; do wait "$p"; done

# ---- 5. wait for /healthz of every service through the gateway ----
c_info "waiting for health checks through the gateway"
bad=0
for s in "${SERVICES[@]}"; do
  if wait_http "http://localhost:$GATEWAY_PORT/svc/$s/healthz" 120; then c_ok "$s"; else c_fail "$s did not become healthy (docker logs nexus-$s)"; bad=1; fi
done
[ "$bad" = 1 ] && exit 1

# ---- 6. frontend ----
if [ "$FRONTEND" = 1 ]; then
  cd "$ROOT/frontend"
  [ -d node_modules ] || { c_info "installing frontend dependencies"; npm install --no-audit --no-fund >"$RUN_DIR/npm-install.log" 2>&1; }
  if [ -f "$RUN_DIR/frontend.pid" ] && kill -0 "$(cat "$RUN_DIR/frontend.pid")" 2>/dev/null; then
    c_info "frontend already running (pid $(cat "$RUN_DIR/frontend.pid"))"
  else
    FP="$(pick_port 5173 5174 5175)"
    NEXUS_GATEWAY="http://localhost:$GATEWAY_PORT" BROWSER=none nohup npx vite --port "$FP" --strictPort >"$RUN_DIR/frontend.log" 2>&1 &
    echo $! >"$RUN_DIR/frontend.pid"; echo "$FP" >"$RUN_DIR/frontend.port"
    wait_http "http://localhost:$FP/" 60 || { c_fail "frontend did not start, see .run/frontend.log"; exit 1; }
  fi
  FPORT="$(cat "$RUN_DIR/frontend.port")"
  cd "$ROOT"
fi

echo
c_ok "NEXUS is up"
[ "$FRONTEND" = 1 ] && echo "    console      http://localhost:${FPORT}"
echo "    gateway      http://localhost:$GATEWAY_PORT   (try /api/v1/events, /svc/<service>/healthz)"
echo "    traefik      http://localhost:$TRAEFIK_DASHBOARD_PORT"
echo "    rabbitmq     http://localhost:$RABBITMQ_MGMT_PORT   (user nexus, password in .env)"
echo "    minio        http://localhost:$MINIO_CONSOLE_PORT"
echo "    smoke test   scripts/smoke.sh        stop: scripts/stop-all.sh"
