#!/usr/bin/env python3
"""Regenerates every service's Dockerfile, docker-compose.yml and .env.example from one table.
Run from the repo root:  python3 tools/infra/gen-compose.py
The generated files are committed; edit this script, not them."""
import os, textwrap

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# name, database (postgres name | neo4j | none), traefik path prefixes, extra env, extra volumes, mem limit
SERVICES = [
    ("identity-access", "identity", ["/api/v1/auth"], {"DEMO_MODE": "${DEMO_MODE:-true}", "DEMO_CONTROLLER_PASSWORD": "${DEMO_CONTROLLER_PASSWORD:-nexus-demo}", "DEMO_RESPONDER_PASSWORD": "${DEMO_RESPONDER_PASSWORD:-nexus-demo}", "DEMO_CITIZEN_PASSWORD": "${DEMO_CITIZEN_PASSWORD:-nexus-demo}"}, [], "128m"),
    ("graph-engine", "neo4j", ["/api/v1/graph", "/api/v1/routes", "/api/v1/topology"], {"ROADS_FILE": "/frontend-public/roads.json"}, ["../../frontend/public:/frontend-public:ro"], "768m"),
    ("iot-broker", "events", ["/api/v1/telemetry", "/api/v1/events", "/ws"], {}, [], "192m"),
    ("predictive-analytics", None, ["/api/v1/hazard", "/api/v1/analytics"], {"GRAPH_URL": "http://nexus-graph-engine:8080", "TRAFFIC_URL": "http://nexus-traffic-control:8080"}, [], "128m"),
    ("traffic-control", "traffic", ["/api/v1/roads"], {"GRAPH_URL": "http://nexus-graph-engine:8080"}, [], "128m"),
    ("environmental-monitor", "environment", ["/api/v1/environment"], {}, [], "128m"),
    ("emergency-dispatch", "dispatch", ["/api/v1/dispatch", "/api/v1/hospitals", "/api/v1/units", "/api/v1/shelters", "/api/v1/pharmacies"], {"GRAPH_URL": "http://nexus-graph-engine:8080"}, [], "192m"),
    ("citizen-reporting", "reports", ["/api/v1/sos", "/api/v1/reports", "/api/v1/incidents"], {}, [], "128m"),
    ("media-storage", None, ["/api/v1/media"], {"S3_ENDPOINT": "nexus-minio:9000", "AWS_ACCESS_KEY_ID": "${MINIO_ROOT_USER:-nexus}", "AWS_SECRET_ACCESS_KEY": "${MINIO_ROOT_PASSWORD:-nexus-minio-secret}", "MEDIA_BUCKET": "nexus-media"}, [], "128m"),
    ("notification-gateway", "alerts", ["/api/v1/alerts"], {}, [], "128m"),
]

DOCKERFILE = """\
# syntax=docker/dockerfile:1
# Build context is services/ so the shared module (replace nexus/shared => ../shared) is inside it.
FROM golang:1.25-alpine AS build
WORKDIR /src
COPY shared/go.mod shared/go.sum shared/
COPY {svc}/go.mod {svc}/go.sum {svc}/
RUN --mount=type=cache,target=/go/pkg/mod cd {svc} && go mod download
COPY shared shared
COPY {svc} {svc}
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \\
    cd {svc} && CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/{svc} ./cmd

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata && adduser -D -u 10001 app
USER app
COPY --from=build /out/{svc} /usr/local/bin/{svc}
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/{svc}"]
"""

def compose(svc, db, prefixes, env, vols, mem):
    rule = " || ".join([f"PathPrefix(`{p}`)" for p in prefixes] + [f"PathPrefix(`/svc/{svc}`)"])
    e = {
        "PORT": "8080",
        "RABBITMQ_URL": "amqp://${RABBITMQ_USER:-nexus}:${RABBITMQ_PASS:-nexus-rabbit}@nexus-rabbitmq:5672/",
        "REDIS_URL": "redis://nexus-redis:6379/0",
        "JWT_SECRET": "${JWT_SECRET:-dev-only-change-me}",
        "SERVICE_KEY": "${SERVICE_KEY:-dev-service-key}",
        "SEED_DIR": "/seed",
    }
    deps = ""
    if db == "neo4j":
        e["NEO4J_URI"] = f"bolt://nexus-{svc}-neo4j:7687"
        e["NEO4J_USER"] = "neo4j"
        e["NEO4J_PASSWORD"] = "${NEO4J_PASSWORD:-nexus-neo4j}"
    elif db:
        e["DATABASE_URL"] = f"postgres://nexus:${{POSTGRES_PASSWORD:-nexus}}@nexus-{svc}-db:5432/{db}?sslmode=disable"
    e.update(env)
    envs = "\n".join(f"      {k}: \"{v}\"" for k, v in e.items())
    vol = "\n".join(f"      - {v}" for v in ["../../tools/seed/out:/seed:ro"] + vols)
    nets = "      - nexus-net" + ("\n      - private" if db else "")
    dep = ""
    if db:
        dep = "    depends_on:\n      neo4j:\n        condition: service_started\n" if db == "neo4j" else "    depends_on:\n      db:\n        condition: service_healthy\n"
    out = f"""\
# Generated by tools/infra/gen-compose.py. Do not edit by hand.
name: nexus-{svc}
services:
  {svc}:
    build:
      context: ..
      dockerfile: {svc}/Dockerfile
    image: nexus/{svc}:dev
    container_name: nexus-{svc}
    restart: unless-stopped
    mem_limit: {mem}
    env_file:
      - path: .env
        required: false
    environment:
{envs}
    volumes:
{vol}
{dep}    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/healthz"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s
    networks:
{nets}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nexus-net"
      - "traefik.http.routers.{svc}.rule={rule}"
      - "traefik.http.routers.{svc}.entrypoints=web"
      - "traefik.http.services.{svc}.loadbalancer.server.port=8080"
"""
    if db == "neo4j":
        out += f"""
  neo4j:
    image: neo4j:5
    container_name: nexus-{svc}-neo4j
    restart: unless-stopped
    mem_limit: 1100m
    environment:
      NEO4J_AUTH: "neo4j/${{NEO4J_PASSWORD:-nexus-neo4j}}"
      NEO4J_server_memory_heap_initial__size: "512m"
      NEO4J_server_memory_heap_max__size: "512m"
      NEO4J_server_memory_pagecache_size: "256m"
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:7474 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 15s
    networks:
      - private
"""
    elif db:
        out += f"""
  db:
    image: postgres:16-alpine
    container_name: nexus-{svc}-db
    restart: unless-stopped
    mem_limit: 256m
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: "${{POSTGRES_PASSWORD:-nexus}}"
      POSTGRES_DB: {db}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus -d {db}"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
      - private
"""
    out += "\nnetworks:\n  nexus-net:\n    external: true\n    name: nexus-net\n"
    if db:
        out += "  private: {}\n"
        out += "\nvolumes:\n  " + ("neo4j-data" if db == "neo4j" else "pg-data") + ": {}\n"
    return out

def envexample(svc, db, env):
    lines = ["# Copy to .env (gitignored). Real values never go in git.", "PORT=8080",
             "RABBITMQ_URL=amqp://nexus:change-me@localhost:5672/", "REDIS_URL=", "JWT_SECRET=change-me", "SERVICE_KEY=change-me",
             "SEED_DIR=../../tools/seed/out"]
    if db == "neo4j":
        lines += ["NEO4J_URI=bolt://localhost:7687", "NEO4J_USER=neo4j", "NEO4J_PASSWORD=change-me", "ROADS_FILE=../../frontend/public/roads.json"]
    elif db:
        lines += [f"DATABASE_URL=postgres://nexus:change-me@localhost:5432/{db}?sslmode=disable"]
    for k, v in env.items():
        if k in ("ROADS_FILE",):
            continue
        if "${" in v:
            v = "change-me" if "PASSWORD" in k or "SECRET" in k else v.split(":-")[1].rstrip("}")
        lines.append(f"{k}={v}")
    return "\n".join(lines) + "\n"

for svc, db, prefixes, env, vols, mem in SERVICES:
    d = os.path.join(ROOT, "services", svc)
    open(os.path.join(d, "Dockerfile"), "w").write(DOCKERFILE.format(svc=svc))
    open(os.path.join(d, "docker-compose.yml"), "w").write(compose(svc, db, prefixes, env, vols, mem))
    open(os.path.join(d, ".env.example"), "w").write(envexample(svc, db, env))
open(os.path.join(ROOT, "services", ".dockerignore"), "w").write("**/*.md\n**/.env\n**/.env.*\n!**/.env.example\ngo.work\ngo.work.sum\n**/*_test.go\n**/testdata\n")
print("generated", len(SERVICES), "services")
